### ISSUE TITLE
What is error? How it fix

### ISSUE THREAD

**Issue by Apersant1** [breakndenter/scan-automated-nmap-scan-#1]
/opt/nmapbar/nmapbar.rb:116:in `each': Input/output error @ io_fillbuf - fd:5 /dev/pts/0 (Errno::EIO)
        from /opt/nmapbar/nmapbar.rb:116:in `block in <main>'
    from /opt/nmapbar/nmapbar.rb:115:in `spawn'
        from /opt/nmapbar/nmapbar.rb:115:in `<main>'

**Comment by breakndenter** [comment]
I am sorry but I was unable to preproduce the issue. Maybe start from scratch ... (clear bashrc at the bottom where it starts with "alias ports ...", and start with fresh nmapbar.rb following the instructions)
